[package]
name = "server"
version = "0.1.0"
edition = "2024"
authors = ["jeff.cofos@gmail.com"]

[dependencies]
ntex = { version = "2.0", features = ["tokio"] }

[dev-dependencies]
thiserror = { version = "2.0.12", features = ["default"] }
